### ISSUE TITLE
connect_kwargs.passphrase and sudo.password per host configuration

### ISSUE THREAD

**Issue by slippers** [fabric/fabric#2095]
my local ~/.fabric.yaml file contains credentials for my one server.
```
connect_kwargs:
    passphrase: xyzzy
sudo:
    password: lol
```
now i want to specify a set of these one per each host. 

how do i articulate this information?  should i move to using a more robust fabric.py.
